//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace cdz360Tools.Contracts
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SvrRetMessage", Namespace="http://schemas.datacontract.org/2004/07/cdz360Tools.Contracts")]
    public partial class SvrRetMessage : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private bool ExcuResultField;
        
        private string MessageField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool ExcuResult
        {
            get
            {
                return this.ExcuResultField;
            }
            set
            {
                this.ExcuResultField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message
        {
            get
            {
                return this.MessageField;
            }
            set
            {
                this.MessageField = value;
            }
        }
    }
}


[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(ConfigurationName="ICzd360DuplexServices", CallbackContract=typeof(ICzd360DuplexServicesCallback))]
public interface ICzd360DuplexServices
{
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICzd360DuplexServices/CheckoutChannel", ReplyAction="http://tempuri.org/ICzd360DuplexServices/CheckoutChannelResponse")]
    cdz360Tools.Contracts.SvrRetMessage CheckoutChannel(System.DateTime time);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICzd360DuplexServices/CheckoutChannel", ReplyAction="http://tempuri.org/ICzd360DuplexServices/CheckoutChannelResponse")]
    System.Threading.Tasks.Task<cdz360Tools.Contracts.SvrRetMessage> CheckoutChannelAsync(System.DateTime time);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICzd360DuplexServices/ChargingPileOrder", ReplyAction="http://tempuri.org/ICzd360DuplexServices/ChargingPileOrderResponse")]
    cdz360Tools.Contracts.SvrRetMessage ChargingPileOrder(byte gunSeqNo, byte OrderChargeType, string deviceSeqNo, string cardSeqNo, string phoneNumber, System.DateTime startTime, System.DateTime endTime);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICzd360DuplexServices/ChargingPileOrder", ReplyAction="http://tempuri.org/ICzd360DuplexServices/ChargingPileOrderResponse")]
    System.Threading.Tasks.Task<cdz360Tools.Contracts.SvrRetMessage> ChargingPileOrderAsync(byte gunSeqNo, byte OrderChargeType, string deviceSeqNo, string cardSeqNo, string phoneNumber, System.DateTime startTime, System.DateTime endTime);
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public interface ICzd360DuplexServicesCallback
{
    
    [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/ICzd360DuplexServices/CheckoutChannelMessage")]
    void CheckoutChannelMessage(string message);
    
    [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/ICzd360DuplexServices/ChargingPileOrderMesage")]
    void ChargingPileOrderMesage(string deviceSeqNo, short gunSqNo, string orderSeqNo, bool orderStatus);
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public interface ICzd360DuplexServicesChannel : ICzd360DuplexServices, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class Czd360DuplexServicesClient : System.ServiceModel.DuplexClientBase<ICzd360DuplexServices>, ICzd360DuplexServices
{
    
    public Czd360DuplexServicesClient(System.ServiceModel.InstanceContext callbackInstance) : 
            base(callbackInstance)
    {
    }
    
    public Czd360DuplexServicesClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName) : 
            base(callbackInstance, endpointConfigurationName)
    {
    }
    
    public Czd360DuplexServicesClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, string remoteAddress) : 
            base(callbackInstance, endpointConfigurationName, remoteAddress)
    {
    }
    
    public Czd360DuplexServicesClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(callbackInstance, endpointConfigurationName, remoteAddress)
    {
    }
    
    public Czd360DuplexServicesClient(System.ServiceModel.InstanceContext callbackInstance, System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(callbackInstance, binding, remoteAddress)
    {
    }
    
    public cdz360Tools.Contracts.SvrRetMessage CheckoutChannel(System.DateTime time)
    {
        return base.Channel.CheckoutChannel(time);
    }
    
    public System.Threading.Tasks.Task<cdz360Tools.Contracts.SvrRetMessage> CheckoutChannelAsync(System.DateTime time)
    {
        return base.Channel.CheckoutChannelAsync(time);
    }
    
    public cdz360Tools.Contracts.SvrRetMessage ChargingPileOrder(byte gunSeqNo, byte OrderChargeType, string deviceSeqNo, string cardSeqNo, string phoneNumber, System.DateTime startTime, System.DateTime endTime)
    {
        return base.Channel.ChargingPileOrder(gunSeqNo, OrderChargeType, deviceSeqNo, cardSeqNo, phoneNumber, startTime, endTime);
    }
    
    public System.Threading.Tasks.Task<cdz360Tools.Contracts.SvrRetMessage> ChargingPileOrderAsync(byte gunSeqNo, byte OrderChargeType, string deviceSeqNo, string cardSeqNo, string phoneNumber, System.DateTime startTime, System.DateTime endTime)
    {
        return base.Channel.ChargingPileOrderAsync(gunSeqNo, OrderChargeType, deviceSeqNo, cardSeqNo, phoneNumber, startTime, endTime);
    }
}
